# Generated by Django 6.0.7 on 2026-07-27 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_course_discount_price_course_early_bird_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="discount_amount",
            field=models.PositiveIntegerField(default=0, verbose_name="分攤折扣"),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="paid_amount",
            field=models.PositiveIntegerField(default=0, verbose_name="實付金額"),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="price",
            field=models.PositiveIntegerField(verbose_name="購買當下售價"),
        ),
    ]
