# Generated by Django 6.0.5 on 2026-08-06 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_course_access_duration_days_course_intro_video_file_and_more'),
    ]

    # 共用雲端資料庫的 main_orderitem 已經有 discount_amount / paid_amount 這兩欄
    # （另一位組員在自己的分支做訂單金額功能時，直接對共用 DB 加的欄位，
    # 該分支程式碼還沒合併進這個 repo）。這裡只同步 Django 的 migration 狀態，
    # 不對資料庫下 ALTER TABLE，避免「欄位已存在」的錯誤。
    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='orderitem',
                    name='discount_amount',
                    field=models.PositiveIntegerField(default=0, verbose_name='此項折扣金額'),
                ),
                migrations.AddField(
                    model_name='orderitem',
                    name='paid_amount',
                    field=models.PositiveIntegerField(default=0, verbose_name='此項實付金額'),
                ),
            ],
            database_operations=[],
        ),
    ]
