# Generated by Django 4.2.30 on 2026-09-13 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_courseanswer_is_ai_generated'),
        ('main', '0020_lessonmaterial_material_type_and_more'),
    ]

    operations = [
    ]
