"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# 讀取專案根目錄的 .env（放共用資料庫連線資訊等機密，不會進版控）
load_dotenv(BASE_DIR.parent / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-!myfgv08#hs01651h)z0w9m48ywynf10)135pb!5tnmn%zug2n',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = ['127.0.0.1', 'localhost']
# 正式部署時把 EB／自訂網域填進 ALLOWED_HOSTS 環境變數（逗號分隔），本機不填照常跑。
ALLOWED_HOSTS += [h.strip() for h in os.environ.get('ALLOWED_HOSTS', '').split(',') if h.strip()]

# 表單 POST（登入、結帳等）在 https 網域需要信任來源，否則會 CSRF 失敗。
# 例：CSRF_TRUSTED_ORIGINS=https://xxx.elasticbeanstalk.com,https://your-domain.com
CSRF_TRUSTED_ORIGINS = [
    o.strip() for o in os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',') if o.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'main',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise 讓 gunicorn 也能送靜態檔（本機 runserver 不受影響）。
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'main.context_processors.nav_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'

# @login_required 未登入時導向本站登入頁（預設是不存在的 /accounts/login/）。
LOGIN_URL = 'login'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# 連線資訊全部從環境變數(.env)讀取；沒設定時 fallback 回本機預設，
# 這樣沒建 .env 的人仍可跑本機 MySQL，設了 .env 就會連到共用雲端資料庫。
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ.get('DB_NAME', 'course_platform_db'),
        'USER': os.environ.get('DB_USER', 'root'),
        'PASSWORD': os.environ.get('DB_PASSWORD', '0000'),
        'HOST': os.environ.get('DB_HOST', '127.0.0.1'),
        'PORT': os.environ.get('DB_PORT', '3306'),
        # 遠端資料庫每次重新建立連線很花時間，保持連線 60 秒重複使用
        'CONN_MAX_AGE': int(os.environ.get('DB_CONN_MAX_AGE', '60')),
        'OPTIONS': {
            'charset': 'utf8mb4',
        },
    }
}

# 部分雲端 MySQL（如 Aiven）需要 TLS，把平台給的 ca.pem 路徑填在 DB_SSL_CA 即可。
_db_ssl_ca = os.environ.get('DB_SSL_CA')
if _db_ssl_ca:
    DATABASES['default']['OPTIONS']['ssl'] = {'ca': _db_ssl_ca}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'zh-hant'

TIME_ZONE = 'Asia/Taipei'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
# collectstatic 會把靜態檔集中到這裡，供 WhiteNoise 在正式環境送出。
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# 儲存後端：靜態檔一律走 WhiteNoise（壓縮＋帶 hash 快取）。
# 上傳檔（media）預設存本機磁碟；一旦設了 AWS_STORAGE_BUCKET_NAME 就改存 S3
# —— 因為 EB／容器的磁碟是暫時的，重新部署後本機上傳的檔案會消失。
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

AWS_STORAGE_BUCKET_NAME = os.environ.get('AWS_STORAGE_BUCKET_NAME', '')
if AWS_STORAGE_BUCKET_NAME:
    AWS_S3_REGION_NAME = os.environ.get('AWS_S3_REGION_NAME', '')
    # 金鑰用 EB/EC2 的 IAM Role 提供（boto3 會自動取用），不必設；
    # 只有本機測試連 S3 時才用環境變數帶入一組金鑰。
    _ak = os.environ.get('AWS_ACCESS_KEY_ID', '')
    _sk = os.environ.get('AWS_SECRET_ACCESS_KEY', '')
    if _ak and _sk:
        AWS_ACCESS_KEY_ID = _ak
        AWS_SECRET_ACCESS_KEY = _sk
    # 東京區的新 bucket 需要 SigV4 + 區域端點，否則簽名網址會走全球端點被 307 轉址。
    AWS_S3_SIGNATURE_VERSION = 's3v4'
    if AWS_S3_REGION_NAME:
        # 指定區域端點，讓簽章與網址主機一致、直達不轉址。
        AWS_S3_ENDPOINT_URL = f'https://s3.{AWS_S3_REGION_NAME}.amazonaws.com'
    # 私有 bucket + 簽名網址（AWS_QUERYSTRING_AUTH 預設 True）：
    # 圖片網址帶簽章、每次算，不必把 bucket 設成公開存取。
    STORAGES['default'] = {
        'BACKEND': 'storages.backends.s3.S3Storage',
        'OPTIONS': {'location': 'media'},
    }

# Email（密碼重設信）
# 設了 EMAIL_HOST_USER 就走真的 SMTP；沒設就把信印在終端機。
# 跟資料庫連線同一個哲學：有 .env 用真的，沒有也能跑，測試不會真的寄信。
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')

if EMAIL_HOST_USER:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
    EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
    EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
else:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL') or EMAIL_HOST_USER or 'noreply@example.com'

# 快速登入（Google / LINE Login）
# 到 Google Cloud Console / LINE Developers 申請後填入 .env，本機沒填就不會顯示對應按鈕。
GOOGLE_OAUTH_CLIENT_ID = os.environ.get('GOOGLE_OAUTH_CLIENT_ID', '')
GOOGLE_OAUTH_CLIENT_SECRET = os.environ.get('GOOGLE_OAUTH_CLIENT_SECRET', '')

LINE_LOGIN_CHANNEL_ID = os.environ.get('LINE_LOGIN_CHANNEL_ID', '')
LINE_LOGIN_CHANNEL_SECRET = os.environ.get('LINE_LOGIN_CHANNEL_SECRET', '')

# AI 課程助教：支援 Anthropic Claude 與 Google Gemini，兩個金鑰都沒設定時
# 前台會顯示「未啟用」，不影響其他功能。同時設定兩個金鑰時可用 AI_PROVIDER
# （'gemini' 或 'anthropic'）明確指定，沒指定就優先用 Gemini。
ANTHROPIC_API_KEY = os.environ.get('ANTHROPIC_API_KEY', '')
AI_ASSISTANT_MODEL = os.environ.get('AI_ASSISTANT_MODEL', 'claude-opus-5')
GEMINI_API_KEY = os.environ.get('GEMINI_API_KEY', '')
GEMINI_MODEL = os.environ.get('GEMINI_MODEL', 'gemini-3.8-flash')
AI_PROVIDER = os.environ.get('AI_PROVIDER', '')

# 沒有這行時 makemigrations 會依環境的 Django 版本猜預設值，導致每個模型的
# id 欄位在不同機器上跑出不同的遷移。既有的遷移檔全部是 BigAutoField，
# 明確設定與資料庫現況一致，避免產生不相干的 alter id 遷移。
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
